// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct wifi s_wifi = {"pass", "name"};
void glue_get_wifi(struct wifi *data) {
  *data = s_wifi;  // Sync with your device
}
void glue_set_wifi(struct wifi *data) {
  s_wifi = *data; // Sync with your device
}

static struct mqtt s_mqtt = {"password", "login", "demo"};
void glue_get_mqtt(struct mqtt *data) {
  *data = s_mqtt;  // Sync with your device
}
void glue_set_mqtt(struct mqtt *data) {
  s_mqtt = *data; // Sync with your device
}

static struct rs485 s_rs485 = {12};
void glue_get_rs485(struct rs485 *data) {
  *data = s_rs485;  // Sync with your device
}
void glue_set_rs485(struct rs485 *data) {
  s_rs485 = *data; // Sync with your device
}

static struct uchet s_uchet = {42};
void glue_get_uchet(struct uchet *data) {
  *data = s_uchet;  // Sync with your device
}
void glue_set_uchet(struct uchet *data) {
  s_uchet = *data; // Sync with your device
}

static struct rest s_rest = {42, 42};
void glue_get_rest(struct rest *data) {
  *data = s_rest;  // Sync with your device
}
void glue_set_rest(struct rest *data) {
  s_rest = *data; // Sync with your device
}
